# Dependencies
markdown:         kramdown
highlighter:      rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge


# Setup
title:            Incio's Knowledge Repository for me
tagline:          "나를 위한 지식저장소 (Incio's Knowledge Repository for me)"
description:      "나를 위한 지식저장소 (Incio's Knowledge Repository for me)"
url:              https://inci-o.github.io
baseurl:          ''

version: 0.5.0

# bootstrap
sass:
  load_paths:
    - _sass
    - ./node_modules/bootstrap/scss

# Exclude from processing.
exclude:
  - node_modules

github:
  repo:           https://github.com/inci-o

author:
  name:           'Incio'
  url:            https://inci-o.github.io

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

lang:
  ko-KR

# Sidebar link settings
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
comments: true

disqus:
  shortname: incio

google_analytics: UA-155325121-1

permalink: /:categories/:title