# Dependencies
markdown:         kramdown
highlighter:      rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge


# Setup
title:            Incio's
tagline:          'Home'
description:      "블로그명을 아직 못 정했음.."
url:              https://inci-o.github.io
baseurl:          ''
                  # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.
version: 0.2.0

# bootstrap
sass:
  load_paths:
    - _sass
    - ./node_modules/bootstrap/scss

# Exclude from processing.
exclude:
  - node_modules

github:
  repo:           https://github.com/inci-o

author:
  name:           'Incio'
  url:            https://inci-o.github.io

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Sidebar link settings
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
comments: true

disqus:
  shortname: incio

google_analytics: UA-155325121-1